project:
  type: website
  output-dir: docs              #defaults to _site
  # render:
  #   - index.qmd
  #   - conferences/*.qmd
  #   - research/*.qmd
  #   - software/*.qmd
  #   - posts/*.qmd
  
  preview:
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true
  
  # to generate babelquarto site use babelquarto::render_website()
  # Preview the website with servr::httw("docs")
  
# Metadata stuff
pagetitle: "{{< meta title >}} | Andreas Schneider"
author-meta: "Andreas Schneider"

website:
  title: "Andreas Schneider"
  description: "Professional and academic website of Andreas Schneider."
  back-to-top-navigation: true
  favicon: assets/img/favicon.png
  #search: true (defaults to glass)
  search:
    location: navbar
    type: overlay
  # cookie-consent:
  #   type: express
  #   style: simple
  #   palette: light
  # prefs-text: "This site uses Google Analytics to analyse website traffic and improve your expirience of the site."
  google-analytics:
     tracking-id: "G-7XFKWH2BH0"
     anonymize-ip: false 
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  # twitter-card:
  #   creator: "@aschneiderpy"
  #   site: "@aschneiderpy"
  #   image: assets/img/as.png
  #   card-style: summary  
  #   image-height: 150
  #   image-width: 150
  
  page-footer:
    #background: light
    foreground: "#ffffff"
    border: true
    left: "© 2025 Andreas Schneider" 
    center: "Made with ❤️ and Quarto"
  navbar:
    right:
      - text: About
        href: about.qmd
      # - text: Home
      #   href: index.qmd
      - text: Research
        menu:
          - aria-label: Publications
          - href: research/index.qmd
          - aria-label: Conferences
          - href: conferences/index.qmd
      - text: Posts
        menu:
          - text: All posts
            href: posts/index.qmd
          - text: English
            href: posts/en.qmd
          - text: Español
            href: posts/es.qmd
      - text: Software
        href: software/index.qmd
      - href: contact.qmd
        
    tools:
      - icon: github
        href: https://github.com/schneiderpy
format:
  html:
    theme: styles.scss
    #theme: [default, styles.scss]
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    #footnotes-hover: true 
    
# babelquarto:
#   languagelinks: navbar
#   languagecodes:
#   - name: es
#     text: "Español"
#   - name: en
#     text: "English"
#   mainlanguage: 'en'
#   languages: ['es']
# title-es: "Andreas Schneider"
# description-es: "Sitio web profesional y académico de Andreas Schneider."
# author-es: "Andreas Schneider"

lang: en
